baseURL = "https://tmcitmap.pages.dev"
languageCode = "ja"
title = "Floormap"
theme = "floooor"
googleAnalytics = ""

[menu]

  [[menu.main]]
    identifier = "home"
    name = "ホーム"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "home"
    name = "各階"
    url = "/floor/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true