baseURL = "https://tmcitmap.pages.dev"
languageCode = "ja"
title = "Floormap"
theme = "floooor"
googleAnalytics = ""

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true